### ISSUE TITLE
Burn Bootloader - Error

### ISSUE THREAD

**Issue by jpenner64** [sonydevworld/spresense#10]
**Received the following error once reaching the Bootloader step in end user process:**

**[3224] Failed to execute script flash_writer**
>>> Install files ...
Traceback (most recent call last):
  File "flash_writer.py", line 504, in <module>
  File "flash_writer.py", line 477, in main
  File "flash_writer.py", line 378, in install_files
FileNotFoundError: [Errno 2] No such file or directory: '___REMOVE___/spresense_dvt/firmware/loader.espk'
Error while burning bootloader.

Hardware setup: Windows 10
Software version used: Arduino IDE - 1.6.13

**Resolution:** Since already having version installed, Boards Manager recognized this, and Ignored updating. After updated the SDK, and issue was resolved.

**Comment by takayoshi-k** [comment]
Now it is fixed.
