### ISSUE TITLE
TEMP_DIRECTORY setting of libjpeg

### ISSUE THREAD

**Issue by satosisotas** [sonydevworld/spresense#301]
This line in the Makefile of libjpeg:
https://github.com/sonydevworld/spresense/blob/master/externals/libjpeg/Makefile#L49

I think this code should be (append a slash at the end of the directory):
```
CFLAGS += -DTEMP_DIRECTORY=\"/mnt/spif/\"
```

**Comment by SPRESENSE** [comment]
@satosisotas Thank you for pointing that out. we will fix it.

**Comment by SPRESENSE** [comment]
Fix https://github.com/sonydevworld/spresense/issues/301 on `develop` branch.

**Comment by SPRESENSE** [comment]
Released v2.4.0.
