### ISSUE TITLE
Using the code with sensor data as model input

### ISSUE THREAD

**Issue by AliRSajun** [sonydevworld/spresense#406]
Hello.

How could the code be modified to pass raw sensor data to a compiled model.
I assume the loading would be changed but what would replace it? How would this data be input to the model?
Additionally, could we load a csv and pass it line by line?

Thank you.

**Comment by SPRESENSE** [comment]
Hi @AliRSajun san
If you are clear on what you want to do, please be specific in your questions and use the Spresense Forum.
https://forum.developer.sony.com/category/5/spresense

There are several DNN examples using NNC or TensorFlow Lite, and the NuttX Real-Time OS used by the Spresense SDK is POSIX compliant, so file operation as CSV files is also supported as standard.

Thanks.
