### ISSUE TITLE
Issue with SDK getting stated guide

### ISSUE THREAD

**Issue by MicroTensor** [sonydevworld/spresense#426]
Hi,

Today for the first time I was following SDK getting stated guide, and as per instructions at https://developer.sony.com/develop/spresense/docs/sdk_set_up_en.html#_configuration_instructions
should be running `tools/config.py examples/hello` but the latest SDK has layout of `apps/examples/hello`
and when I ran `tools/config.py apps/examples/hello` get error 
![image](https://user-images.githubusercontent.com/99717856/165000905-f7e580ac-d906-429d-8069-74973b8568a5.png)

**Comment by SPRESENSE** [comment]
Hi,

The arguments of the `tools/config.py` are documented correctly.
```
$ cd spresense/sdk
$ tools/config.py examples/hello
```
The `examples/hello` argument specifies the configuration name under `spresense/sdk/configs`, which is not the path to the source code. And the available arguments can be listed in `tools/config.py -l`.

Thanks.

**Comment by KazuyaHioki** [comment]
Close #426
