### ISSUE TITLE
Unable to run spresense SDK example "bluetooth_le_central" with bluetooth module HM-10

### ISSUE THREAD

**Issue by 1349636970** [sonydevworld/spresense#481]
![image](https://user-images.githubusercontent.com/24194836/182756684-88acc72c-247e-4050-bba5-afda6989bd92.png)
HM-10 Pinout

![image](https://user-images.githubusercontent.com/24194836/182756718-3a749801-c209-4b13-b088-5d8b8adbd574.png)
Spresense Pinout

Hi Community,
I am new to Microcontroller. Hope I explain my problem clearly enough.
I connected the RXD and TXD on my HM-10 to UART2_RX and UART2_TX on spresense. Then I try to build and fresh the "[bluetooth_le_central](https://github.com/sonydevworld/spresense/tree/master/examples/bluetooth_le_central)" example on the spresense SDK Github repo.
The code is successfully fresh into spresense but when I run it. The nuttx give me this ERROR:
[BT][Common] Initialization failed(HAL initialize failed)
After checking the documentation and debugging. I found out that the Bluetooth module initialize is failed
I have an error on this [function](https://developer.sony.com/develop/spresense/developer-tools/api-reference/api-references-spresense-sdk/bt__common_8h.html#ac7e034552af4e5b3f5ceb2d721592333)

![image](https://user-images.githubusercontent.com/24194836/182756759-10c60b03-9cb1-4a63-aba4-5cd9c7d8a5d6.png)
I am looking for a solution or some clues.

Thanks,
Zhenyu

FYI,
I used the same setup on Arduino IDE and could enter the AT mode of the Bluetooth. I think that means I got the pin right.

**Comment by SPRESENSE** [comment]
Dear @1349636970 san,

Spresense only supports BCM20706 and NRF52 on bluetooth device, right now.
When using this Bluetooth device, it is necessary to implement code to send and receive AT commands directly via UART2.

Best Regards,
Spresense team
