### ISSUE TITLE
<cmath> not supported for c++

### ISSUE THREAD

**Issue by slipperyseal** [sonydevworld/spresense#53]
While `math.h` functions are available to C programs, the equiveant (or bridging functions) do not appear to be able to C++ programs.  This may not strictly be a bug, just an unsupported feature. The nuttx mainline has the same issue unless you active "Standand math library" option (on ubuntu with gcc). This option issue exists in the spresense build system but is not enabled in Kconfig for some reason.  I have been able to work around the issue in my project by creating bridging functions in C.

To reproduce add.. (i added spaces because of markup)

#include < cmath >

to `helloxx_main.cxx` in the `helloxx` example.

```
CXX:  helloxx_main.cxx
In file included from /home/seal/sony/spresense/sdk/include/arch/math.h:41:0,
                 from /home/seal/sony/spresense/nuttx/include/math.h:52,
                 from /home/seal/sony/spresense/nuttx/include/cxx/cmath:46,
                 from helloxx_main.cxx:44:
/home/seal/spresenseenv/usr/arm-none-eabi/include/c++/7.3.1/math.h:38:12: error: 'std::abs' has not been declared
 using std::abs;
            ^~~
/home/seal/spresenseenv/usr/arm-none-eabi/include/c++/7.3.1/math.h:39:12: error: 'std::acos' has not been declared
 using std::acos;
            ^~~~
/home/seal/spresenseenv/usr/arm-none-eabi/include/c++/7.3.1/math.h:40:12: error: 'std::asin' has not been declared
 using std::asin;
            ^~~~
```
 etc...

**Comment by SPRESENSE** [comment]
In the NuttX 10.1 release, an option to use "LLVM libc++ C++ Standard Library" has been introduced.
Spresense SDK is planed to update the NuttX version to 10.1 on next release, which version is SDK v2.3.
But you can try it by using "develop" branch on spresense.git repository.

To confirm `<cmath>` is available in the following way:

```
$ ./tools/config.py examples/helloxx feature/libcxx
$ make
```

Thanks.

**Comment by SPRESENSE** [comment]
SDK v2.3 has been released and this issue has been resolved.
