### ISSUE TITLE
How can I setup  spresense board with RFID module.

### ISSUE THREAD

**Issue by Hrithik2212** [sonydevworld/spresense#624]
I want to develop an application with RFID , however it seems RFID is not compatible with spresense (Arduino IDE ,I mean there is no specific library). I would like to know if its possible to  integrate them , I don't have any clue and need references so I could learn to integrate them if they can be integrated. Thank You

**Comment by SPRESENSE** [comment]
I haven't develop RFID, so I looked for it within NuttX and found a driver and an example code.
- nuttx/drivers/contactless/mfrc522.c
- sdk/apps/examples/rfid_readuid/rfid_readuid.c
It might be helpful to you.
Thanks

**Comment by SPRESENSE** [comment]
Close as answered.
